---
- name: Install Git, Curl, and jq on Windows 10
  hosts: windows
  gather_facts: no
  tasks:
    - name: Install Git using Chocolatey
      win_chocolatey:
        name: git
        state: present
      vars:
        ansible_winrm_server_cert_validation: ignore

    - name: Install Curl using Chocolatey
      win_chocolatey:
        name: curl
        state: present
      vars:
        ansible_winrm_server_cert_validation: ignore
          
    - name: Install jq using Chocolatey
      win_chocolatey:
        name: jq
        state: present
      vars:
        ansible_winrm_server_cert_validation: ignore
          
    - name: Install Node.js using Chocolatey
      win_chocolatey:
        name: nodejs
        state: present
        version: 18.17.0
      vars:
        ansible_winrm_server_cert_validation: ignore          

    - name: Install PM2 using npm
      win_shell: npm install -g pm2        
      vars:
        ansible_winrm_server_cert_validation: ignore

    - name: Install JDK 17 using Chocolatey
      win_chocolatey:
        name: openjdk17
        state: present
      vars:
        ansible_winrm_server_cert_validation: ignore

    - name: Set JAVA_HOME environment variable
      win_environment:
        name: JAVA_HOME
        state: present
        value: "C:\\Program Files\\AdoptOpenJDK\\jdk-17"  # Adjust the path accordingly
        level: machine          
      vars:
        ansible_winrm_server_cert_validation: ignore

    - name: Download nginx
      win_get_url:
        url: "http://nginx.org/download/nginx-1.24.0.zip"
        dest: C:\nginx-1.24.0.zip
      vars:
        ansible_winrm_server_cert_validation: ignore

    - name: Unzip nginx file
      win_unzip:
        src: C:\nginx-1.24.0.zip
        dest: C:\nginx-1.24.0
      vars:
        ansible_winrm_server_cert_validation: ignore

    - name: Download nssm
      win_get_url:
        url: "https://nssm.cc/release/nssm-2.24.zip"
        dest: C:\nssm-2.24.zip
      vars:
        ansible_winrm_server_cert_validation: ignore

    - name: Unzip nssm
      win_unzip:
        src: C:\nssm-2.24.zip
        dest: C:\nssm-2.24
      vars:
        ansible_winrm_server_cert_validation: ignore

    - name: Download Jenkins MSI installer
      win_get_url:
        url: https://get.jenkins.io/windows-stable/2.440.2/jenkins.msi
        dest: C:\jenkins.msi
      vars:
        ansible_winrm_server_cert_validation: ignore        
